language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  - HOST=localhost DATABASE=ride USER=postgres PASSWORD=baraka
services:
  - postgresql
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'baraka';" -U postgres
  - psql -c "CREATE DATABASE ride;" -U postgres
# command to run tests
script:
  - python create_tables.py
  - pytest --cov-report= --cov=V2/ tests
#run coverage tests
after_success:
  - coveralls
  - codecov --token=924ff14f-e9e6-425b-b646-25e12c56be63