language: python

python: '3.6'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test
addons:
  postgresql: "9.4"

addons:
  jwt:
     secure: 'cbbfvfjjfjjjfsjajjkkvsjh4636787531r9898298981'

# Install dependencies
install: 
    - pip install -r requirements.txt
    - pip install coveralls

# Run tests
script: nosetests --with-coverage

after_success: coveralls