language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  - HOST=localhost DATABASE=maintenancetracker USER=postgres PASSWORD=postgres
services:
  - postgresql
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
  - psql -c "CREATE DATABASE maintenancetracker;" -U postgres
# command to run tests
script:
  - python manage.py
  - pytest --cov-report= --cov=app/ tests
#run coverage tests
after_success:
  - coveralls
  - codecov --token=924ff14f-e9e6-425b-b646-25e12c56be63